### ISSUE TITLE
sqLite Latest Version w/ PHP 5.4

### ISSUE THREAD

**Issue by Dazzel** [flourishlib/flourish-classes#45]
Ticket #741 by @rcrisman

I create an sqLite database using flourish but when I go to load the database I get

the sqlite file is version 3.7.7.1

php version 5.4 

```
[05-Mar-2012 16:40:00 UTC] PHP Fatal error:  Uncaught exception 'fConnectivityException' with message 'The database specified does not appear to be a valid SQLite v2.1 or v3 database' in E:\public_html\inc\flourish\fDatabase.php:956
Stack trace:
#0 E:\public_html\inc\flourish\fDatabase.php(331): fDatabase->determineExtension()
#1 E:\public_html\inc\init.php(9): fDatabase->__construct('sqlite', 'E:\public_html/...')
#2 E:\public_html\index.php(2): include_once('E:\public_html\...')
#3 {main}
  thrown in E:\public_html\inc\flourish\fDatabase.php on line 956
```

**Comment by Tatsh** [comment]
Will also note that the old sqlite_\* functions have been removed in 5.4.
